// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Vendored from Paseo 0.2.0 packages/app/src/data/acp-provider-catalog.ts.

import 'acp_provider_catalog.dart';

const acpProviderCatalog = <AcpProviderCatalogEntry>[
  AcpProviderCatalogEntry(
    id: "agoragentic-acp",
    title: "Agoragentic",
    description:
        "Agent marketplace with 174+ AI capabilities. Browse, invoke, and pay for agent services settled in USDC on Base L2.",
    version: "1.3.6",
    iconName: "agoragentic-acp",
    installLink: "https://agoragentic.com",
    command: <String>["npx", "-y", "agoragentic-mcp@1.3.6", "--acp"],
  ),
  AcpProviderCatalogEntry(
    id: "amp-acp",
    title: "Amp",
    description: "ACP wrapper for Amp - the frontier coding agent",
    version: "0.7.0",
    iconName: "amp-acp",
    installLink: "https://github.com/tao12345666333/amp-acp",
    command: <String>["amp-acp"],
  ),
  AcpProviderCatalogEntry(
    id: "auggie",
    title: "Auggie CLI",
    description:
        "Augment Code's powerful software agent, backed by industry-leading context engine",
    version: "0.33.0",
    iconName: "auggie",
    installLink: "https://www.augmentcode.com/",
    command: <String>["npx", "-y", "@augmentcode/auggie@0.33.0", "--acp"],
    env: <String, Object?>{"AUGMENT_DISABLE_AUTO_UPDATE": "1"},
  ),
  AcpProviderCatalogEntry(
    id: "autohand",
    title: "Autohand Code",
    description: "Autohand Code - AI coding agent powered by Autohand AI",
    version: "0.2.1",
    iconName: "autohand",
    installLink: "https://www.autohand.ai/cli/",
    command: <String>["npx", "-y", "@autohandai/autohand-acp@0.2.1"],
  ),
  AcpProviderCatalogEntry(
    id: "cline",
    title: "Cline",
    description:
        "Autonomous coding agent CLI - capable of creating/editing files, running commands, using the browser, and more",
    version: "3.0.46",
    iconName: "cline",
    installLink: "https://cline.bot/cli",
    command: <String>["npx", "-y", "cline@3.0.46", "--acp"],
  ),
  AcpProviderCatalogEntry(
    id: "codebuddy-code",
    title: "Codebuddy Code",
    description: "Tencent Cloud's official intelligent coding tool",
    version: "manual",
    iconName: "codebuddy-code",
    installLink: "https://www.codebuddy.cn/cli/",
    command: <String>["codebuddy", "--acp"],
  ),
  AcpProviderCatalogEntry(
    id: "codewhale",
    title: "CodeWhale",
    description: "Terminal coding agent for DeepSeek V4 and open models",
    version: "0.8.55",
    iconName: "codewhale",
    installLink: "https://codewhale.net/",
    command: <String>["codewhale", "serve", "--acp"],
  ),
  AcpProviderCatalogEntry(
    id: "cortex-code",
    title: "Cortex Code",
    description: "Snowflake's Cortex Code coding agent",
    version: "1.0.73",
    iconName: "cortex-code",
    installLink:
        "https://docs.snowflake.com/en/user-guide/cortex-code/cortex-code-cli",
    command: <String>["cortex", "acp", "serve"],
  ),
  AcpProviderCatalogEntry(
    id: "corust-agent",
    title: "Corust Agent",
    description: "Co-building with a seasoned Rust partner.",
    version: "0.5.1",
    iconName: "corust-agent",
    installLink: "https://github.com/Corust-ai/corust-agent-release/releases",
    command: <String>["corust-agent-acp"],
  ),
  AcpProviderCatalogEntry(
    id: "crow-cli",
    title: "crow-cli",
    description: "Minimal ACP Native Coding Agent",
    version: "0.1.23",
    iconName: "crow-cli",
    installLink: "https://crow-ai.dev/",
    command: <String>["crow-cli", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "cursor",
    title: "Cursor",
    description: "Cursor's coding agent",
    version: "2026.03.30",
    iconName: "cursor",
    installLink: "https://docs.cursor.com/en/cli/overview",
    command: <String>["cursor-agent", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "deepagents",
    title: "DeepAgents",
    description:
        "Batteries-included AI coding and general purpose agent powered by LangChain.",
    version: "0.1.20",
    iconName: "deepagents",
    installLink:
        "https://docs.langchain.com/oss/javascript/deepagents/overview",
    command: <String>["npx", "-y", "deepagents-acp@0.1.20"],
  ),
  AcpProviderCatalogEntry(
    id: "devin",
    title: "Devin CLI",
    description: "Cognition's Devin for Terminal via Agent Client Protocol",
    version: "manual",
    iconName: null,
    installLink: "https://cli.devin.ai/docs",
    command: <String>["devin", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "dimcode",
    title: "DimCode",
    description: "A coding agent that puts leading models at your command.",
    version: "0.2.36",
    iconName: "dimcode",
    installLink: "https://dimcode.dev/docs/acp.html",
    command: <String>["npx", "-y", "dimcode@0.2.36", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "dirac",
    title: "Dirac",
    description:
        "Reduces API costs by more than 50%, produces better and faster work. Uses Hash anchored parallel edits, AST manipulation and a whole lot of neat optimizations. Fully Open Source.",
    version: "0.4.22",
    iconName: "dirac",
    installLink: "https://dirac.run",
    command: <String>["npx", "-y", "dirac-cli@0.4.22", "--acp"],
  ),
  AcpProviderCatalogEntry(
    id: "factory-droid",
    title: "Factory Droid",
    description: "Factory Droid - AI coding agent powered by Factory AI",
    version: "0.179.0",
    iconName: "factory-droid",
    installLink: "https://factory.ai/product/cli",
    command: <String>[
      "npx",
      "-y",
      "droid@0.179.0",
      "exec",
      "--output-format",
      "acp-daemon",
    ],
    env: <String, Object?>{
      "DROID_DISABLE_AUTO_UPDATE": "true",
      "FACTORY_DROID_AUTO_UPDATE_ENABLED": "false",
    },
    params: <String, Object?>{"supportsMcpServers": false},
  ),
  AcpProviderCatalogEntry(
    id: "fast-agent",
    title: "fast-agent",
    description:
        "Code and build agents with comprehensive multi-provider support",
    version: "0.9.22",
    iconName: "fast-agent",
    installLink: "https://fast-agent.ai/acp/",
    command: <String>[
      "uvx",
      "--from",
      "fast-agent-acp==0.9.22",
      "fast-agent-acp",
      "-x",
    ],
  ),
  AcpProviderCatalogEntry(
    id: "gemini",
    title: "Gemini CLI",
    description: "Google's official CLI for Gemini",
    version: "0.52.0",
    iconName: "gemini",
    installLink: "https://geminicli.com",
    command: <String>["npx", "-y", "@google/gemini-cli@0.52.0", "--acp"],
  ),
  AcpProviderCatalogEntry(
    id: "glm-acp-agent",
    title: "GLM Agent",
    description:
        "ACP agent powered by Zhipu AI's GLM Coding Plan models (glm-5.1, glm-5-turbo, glm-4.7, glm-4.5-air). Supports streaming, tool calls, mid-session model switching, image input via Z.AI Coding Plan Vision MCP, and session load/fork/resume with on-disk persistence.",
    version: "1.3.0",
    iconName: "glm-acp-agent",
    installLink: "https://github.com/stefandevo/glm-acp-agent",
    command: <String>["npx", "-y", "glm-acp-agent@1.3.0"],
  ),
  AcpProviderCatalogEntry(
    id: "goose",
    title: "goose",
    description:
        "A local, extensible, open source AI agent that automates engineering tasks",
    version: "1.33.1",
    iconName: "goose",
    installLink: "https://block.github.io/goose/",
    command: <String>["goose", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "grok",
    title: "Grok",
    description:
        "xAI's Grok Build agentic coding CLI with plan mode and parallel subagents. Requires a SuperGrok or X Premium+ subscription.",
    version: "0.2.11",
    iconName: "grok",
    installLink: "https://docs.x.ai/build/overview",
    command: <String>["grok", "agent", "stdio"],
  ),
  AcpProviderCatalogEntry(
    id: "hermes",
    title: "Hermes",
    description: "Nous Research self-improving AI agent",
    version: "manual",
    iconName: null,
    installLink:
        "https://hermes-agent.nousresearch.com/docs/user-guide/features/acp",
    command: <String>["hermes", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "junie",
    title: "Junie",
    description: "AI Coding Agent by JetBrains",
    version: "1468.30.0",
    iconName: "junie",
    installLink: "https://junie.jetbrains.com/docs/junie-cli-acp.html",
    command: <String>["junie", "--acp", "true"],
  ),
  AcpProviderCatalogEntry(
    id: "kilo",
    title: "Kilo",
    description: "The open source coding agent",
    version: "7.2.40",
    iconName: "kilo",
    installLink: "https://kilo.ai/docs/code-with-ai/platforms/cli",
    command: <String>["kilo", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "kiro",
    title: "Kiro CLI",
    description: "Amazon's AI coding agent with native ACP support",
    version: "manual",
    iconName: null,
    installLink: "https://kiro.dev/docs/cli/acp/",
    command: <String>["kiro-cli", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "kimi",
    title: "Kimi Code CLI",
    description: "Moonshot AI's open-source terminal coding agent",
    version: "0.11.0",
    iconName: "kimi",
    installLink: "https://github.com/MoonshotAI/kimi-code",
    command: <String>["kimi", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "minion-code",
    title: "Minion Code",
    description:
        "An enhanced AI code assistant built on the Minion framework with rich development tools",
    version: "0.1.44",
    iconName: "minion-code",
    installLink: "https://github.com/femto/minion-code",
    command: <String>[
      "uvx",
      "--from",
      "minion-code==0.1.44",
      "minion-code",
      "acp",
    ],
  ),
  AcpProviderCatalogEntry(
    id: "mistral-vibe",
    title: "Mistral Vibe",
    description: "Mistral's open-source coding assistant",
    version: "2.9.3",
    iconName: "mistral-vibe",
    installLink: "https://github.com/mistralai/mistral-vibe",
    command: <String>["vibe-acp"],
  ),
  AcpProviderCatalogEntry(
    id: "nova",
    title: "Nova",
    description:
        "Nova by Compass AI - a fully-fledged software engineer at your command",
    version: "1.1.29",
    iconName: "nova",
    installLink: "https://www.compassap.ai/portfolio/nova.html",
    command: <String>["npx", "-y", "@compass-ai/nova@1.1.29", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "poolside",
    title: "Poolside",
    description: "Poolside's coding agent",
    version: "1.0.0",
    iconName: "poolside",
    installLink: "https://docs.poolside.ai/cli/pool",
    command: <String>["pool", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "qoder",
    title: "Qoder CLI",
    description: "AI coding assistant with agentic capabilities",
    version: "1.1.4",
    iconName: "qoder",
    installLink: "https://qoder.com",
    command: <String>["npx", "-y", "@qoder-ai/qodercli@1.1.4", "--acp"],
  ),
  AcpProviderCatalogEntry(
    id: "qwen-code",
    title: "Qwen Code",
    description: "Alibaba's Qwen coding assistant",
    version: "0.20.1",
    iconName: "qwen-code",
    installLink: "https://qwenlm.github.io/qwen-code-docs/en/users/overview",
    command: <String>[
      "npx",
      "-y",
      "@qwen-code/qwen-code@0.20.1",
      "--acp",
      "--experimental-skills",
    ],
  ),
  AcpProviderCatalogEntry(
    id: "sigit",
    title: "siGit Code",
    description:
        "Local-first coding agent. Runs entirely on your machine with optional on-device LLM inference via Onde.",
    version: "1.0.3",
    iconName: "sigit",
    installLink: "https://github.com/getsigit/sigit",
    command: <String>["sigit"],
  ),
  AcpProviderCatalogEntry(
    id: "stakpak",
    title: "Stakpak",
    description:
        "Open-source DevOps agent in Rust with enterprise-grade security",
    version: "0.3.80",
    iconName: "stakpak",
    installLink: "https://stakpak.dev/",
    command: <String>["stakpak", "acp"],
  ),
  AcpProviderCatalogEntry(
    id: "traecli",
    title: "TRAE CLI",
    description:
        "ByteDance's official TRAE coding agent with native ACP support",
    version: "manual",
    iconName: "traecli",
    installLink: "https://docs.trae.cn/cli_get-started-with-trae-cli",
    command: <String>["traecli", "acp", "serve"],
  ),
  AcpProviderCatalogEntry(
    id: "vtcode",
    title: "VT Code",
    description:
        "An open-source coding agent with LLM-native code understanding and robust shell safety. Supports multiple LLM providers with automatic failover and efficient context management.",
    version: "0.96.14",
    iconName: "vtcode",
    installLink:
        "https://github.com/vinhnx/VTCode/blob/main/docs/guides/zed-acp.md",
    command: <String>["vtcode", "acp"],
    env: <String, Object?>{"VT_ACP_ENABLED": "1", "VT_ACP_ZED_ENABLED": "1"},
  ),
];
