import 'dart:convert';

import 'package:agent_daemon/src/forge/forge_action_service.dart';
import 'package:agent_daemon/src/forge/forge_cli.dart';
import 'package:agent_daemon/src/forge/forge_resolver.dart';
import 'package:agent_daemon/src/git/git_runner.dart';
import 'package:agent_protocol/agent_protocol.dart';
import 'package:test/test.dart';

void main() {
  test(
    'creates a PR after resolving git context, auth, base, and push',
    () async {
      final git = _FakeGit();
      final forge = _FakeForge((_, args) {
        if (args.first == 'auth') return _ok('');
        if (args.take(3).join(' ') == 'api -X POST') {
          return _json({
            'url': 'https://github.com/acme/repo/pull/9',
            'number': 9,
          });
        }
        return _fail('unexpected: $args');
      });
      final service = ForgeActionService(
        resolver: ForgeResolver(transport: forge),
        runGit: git.run,
      );

      final response = CheckoutPrCreateResponse.fromJson(
        (await service.handle({
          'type': 'checkout_pr_create_request',
          'cwd': '/repo',
          'title': ' Feature ',
          'body': '',
          'requestId': 'create-1',
        }))!,
      );

      expect(response.number, 9);
      expect(response.error, isNull);
      expect(git.calls, contains('push -u origin feature'));
      final create = forge.calls.singleWhere(
        (call) => call.take(3).join(' ') == 'api -X POST',
      );
      expect(create, containsAll(['title=Feature', 'base=main']));
      expect(create, contains('body=Automated PR generated by Tinyrack.'));
    },
  );

  test('fresh status guards merge at execution time', () async {
    var mergeState = 'BLOCKED';
    final git = _FakeGit();
    final forge = _FakeForge((_, args) {
      if (args.first == 'auth') return _ok('');
      if (args.take(2).join(' ') == 'pr list') {
        return _json([
          {
            'number': 9,
            'url': 'https://github.com/acme/repo/pull/9',
            'title': 'Feature',
            'state': 'OPEN',
            'isDraft': false,
            'baseRefName': 'main',
            'headRefName': 'feature',
            'headRefOid': 'abc',
            'mergedAt': null,
            'reviewDecision': null,
            'mergeable': 'MERGEABLE',
            'headRepositoryOwner': {'login': 'acme'},
          },
        ]);
      }
      if (args.take(2).join(' ') == 'api graphql') {
        return _json({
          'data': {
            'repository': {
              'mergeCommitAllowed': true,
              'squashMergeAllowed': true,
              'rebaseMergeAllowed': true,
              'pullRequest': {
                'mergeStateStatus': mergeState,
                'autoMergeRequest': null,
              },
            },
          },
        });
      }
      if (args.take(2).join(' ') == 'pr merge') return _ok('');
      return _fail('unexpected: $args');
    });
    final service = ForgeActionService(
      resolver: ForgeResolver(transport: forge),
      runGit: git.run,
    );

    var response = CheckoutPrMergeResponse.fromJson(
      (await service.handle({
        'type': 'checkout_pr_merge_request',
        'cwd': '/repo',
        'mergeMethod': 'squash',
        'requestId': 'merge-1',
      }))!,
    );
    expect(response.success, isFalse);
    expect(response.error?.code, CheckoutErrorCode.notAllowed);
    expect(
      forge.calls.where((args) => args.take(2).join(' ') == 'pr merge'),
      isEmpty,
    );

    mergeState = 'CLEAN';
    response = CheckoutPrMergeResponse.fromJson(
      (await service.handle({
        'type': 'checkout_pr_merge_request',
        'cwd': '/repo',
        'mergeMethod': 'squash',
        'requestId': 'merge-2',
      }))!,
    );
    expect(response.success, isTrue);
    expect(forge.calls.last, ['pr', 'merge', '9', '--squash']);
  });

  test(
    'returns exact checkout errors for no repo and unsupported messages',
    () async {
      final git = _FakeGit(insideRepo: false);
      final service = ForgeActionService(
        resolver: ForgeResolver(transport: _FakeForge((_, _) => _ok(''))),
        runGit: git.run,
      );
      final response = CheckoutPrCreateResponse.fromJson(
        (await service.handle({
          'type': 'checkout_pr_create_request',
          'cwd': '/not-repo',
          'requestId': '1',
        }))!,
      );
      expect(response.error?.code, CheckoutErrorCode.notGitRepo);
      expect(await service.handle({'type': 'other'}), isNull);
    },
  );

  test('covers detached, remote, auth, and base-resolution failures', () async {
    Future<CheckoutPrCreateResponse> create(
      _FakeGit git,
      _FakeForge forge, {
      String? baseRef,
    }) async {
      final service = ForgeActionService(
        resolver: ForgeResolver(transport: forge),
        runGit: git.run,
      );
      return CheckoutPrCreateResponse.fromJson(
        (await service.handle({
          'type': 'checkout_pr_create_request',
          'cwd': '/repo',
          if (baseRef != null) 'baseRef': baseRef,
          'requestId': '1',
        }))!,
      );
    }

    final detached = await create(
      _FakeGit(branch: ''),
      _FakeForge((_, _) => _ok('')),
    );
    expect(detached.error?.code, CheckoutErrorCode.notAllowed);

    final noRemote = await create(
      _FakeGit(remote: ''),
      _FakeForge((_, _) => _ok('')),
    );
    expect(noRemote.error?.message, contains('origin'));

    final noAuth = await create(
      _FakeGit(),
      _FakeForge((_, args) => args.first == 'auth' ? _fail('401') : _ok('')),
    );
    expect(noAuth.error?.code, CheckoutErrorCode.notAllowed);

    final noBase = await create(
      _FakeGit(symbolicBase: '', mainExists: false, masterExists: false),
      _FakeForge((_, args) => args.first == 'auth' ? _ok('') : _fail('unused')),
    );
    expect(noBase.error?.message, contains('base branch'));

    final fallbackForge = _FakeForge((_, args) {
      if (args.first == 'auth') return _ok('');
      if (args.take(3).join(' ') == 'api -X POST') {
        return _json({
          'url': 'https://github.com/acme/repo/pull/2',
          'number': 2,
        });
      }
      return _fail('unexpected');
    });
    final fallback = await create(
      _FakeGit(symbolicBase: '', mainExists: false, masterExists: true),
      fallbackForge,
      baseRef: 'refs/heads/release',
    );
    expect(fallback.error, isNull);
    expect(
      fallbackForge.calls.expand((args) => args),
      contains('base=release'),
    );
  });

  test('merge reports no current PR and git command failures', () async {
    final noPrForge = _FakeForge((_, args) {
      if (args.first == 'auth') return _ok('');
      if (args.take(2).join(' ') == 'pr list') return _json([]);
      return _fail('unexpected');
    });
    final noPrService = ForgeActionService(
      resolver: ForgeResolver(transport: noPrForge),
      runGit: _FakeGit().run,
    );
    final noPr = CheckoutPrMergeResponse.fromJson(
      (await noPrService.handle({
        'type': 'checkout_pr_merge_request',
        'cwd': '/repo',
        'mergeMethod': 'merge',
        'requestId': '1',
      }))!,
    );
    expect(noPr.error?.message, contains('No pull request'));

    final pushFailure = ForgeActionService(
      resolver: ForgeResolver(
        transport: _FakeForge(
          (_, args) => args.first == 'auth' ? _ok('') : _fail('unused'),
        ),
      ),
      runGit: _FakeGit(pushFails: true).run,
    );
    final failed = CheckoutPrCreateResponse.fromJson(
      (await pushFailure.handle({
        'type': 'checkout_pr_create_request',
        'cwd': '/repo',
        'baseRef': 'main',
        'requestId': '2',
      }))!,
    );
    expect(failed.error?.code, CheckoutErrorCode.unknown);
    expect(failed.error?.message, 'push rejected');

    expect(
      ForgeActionService(
        resolver: ForgeResolver(transport: _FakeForge((_, _) => _ok(''))),
      ).handle({'type': 'other'}),
      completion(isNull),
    );
  });

  test(
    'modern and legacy auto-merge RPCs refresh status and pair responses',
    () async {
      var autoEnabled = false;
      final forge = _FakeForge((_, args) {
        if (args.first == 'auth') return _ok('');
        if (args.take(2).join(' ') == 'pr list') {
          return _json([
            {
              'number': 9,
              'url': 'https://github.com/acme/repo/pull/9',
              'title': 'Feature',
              'state': 'OPEN',
              'isDraft': false,
              'baseRefName': 'main',
              'headRefName': 'feature',
              'headRefOid': 'abc',
              'mergedAt': null,
              'reviewDecision': null,
              'mergeable': 'MERGEABLE',
              'headRepositoryOwner': {'login': 'acme'},
            },
          ]);
        }
        if (args.take(2).join(' ') == 'api graphql') {
          return _json({
            'data': {
              'repository': {
                'autoMergeAllowed': true,
                'mergeCommitAllowed': true,
                'squashMergeAllowed': true,
                'rebaseMergeAllowed': true,
                'pullRequest': {
                  'mergeStateStatus': 'BLOCKED',
                  'autoMergeRequest': autoEnabled
                      ? {'mergeMethod': 'SQUASH'}
                      : null,
                  'viewerCanEnableAutoMerge': true,
                  'viewerCanDisableAutoMerge': true,
                },
              },
            },
          });
        }
        if (args.contains('--auto')) {
          autoEnabled = true;
          return _ok('');
        }
        if (args.contains('--disable-auto')) {
          autoEnabled = false;
          return _ok('');
        }
        return _fail('unexpected: $args');
      });
      final service = ForgeActionService(
        resolver: ForgeResolver(transport: forge),
        runGit: _FakeGit().run,
      );

      final enabled = CheckoutForgeSetAutoMergeResponse.fromJson(
        (await service.handle({
          'type': CheckoutForgeSetAutoMergeRequest.modernType,
          'cwd': '/repo',
          'enabled': true,
          'mergeMethod': 'squash',
          'requestId': 'enable',
        }))!,
      );
      expect(enabled.type, CheckoutForgeSetAutoMergeResponse.modernType);
      expect(enabled.success, isTrue);
      expect(autoEnabled, isTrue);

      final disabled = CheckoutForgeSetAutoMergeResponse.fromJson(
        (await service.handle({
          'type': CheckoutForgeSetAutoMergeRequest.legacyGithubType,
          'cwd': '/repo',
          'enabled': false,
          'requestId': 'disable',
        }))!,
      );
      expect(disabled.type, CheckoutForgeSetAutoMergeResponse.legacyGithubType);
      expect(disabled.success, isTrue);
      expect(autoEnabled, isFalse);
    },
  );

  test('auto-merge enforces mergeMethod presence and absence', () async {
    final forge = _FakeForge((_, args) {
      if (args.first == 'auth') return _ok('');
      if (args.take(2).join(' ') == 'pr list') {
        return _json([
          {
            'number': 9,
            'url': 'https://github.com/acme/repo/pull/9',
            'title': 'Feature',
            'state': 'OPEN',
            'isDraft': false,
            'baseRefName': 'main',
            'headRefName': 'feature',
            'headRefOid': 'abc',
            'mergedAt': null,
            'reviewDecision': null,
            'mergeable': 'UNKNOWN',
            'headRepositoryOwner': {'login': 'acme'},
          },
        ]);
      }
      if (args.take(2).join(' ') == 'api graphql') {
        return _json({
          'data': {
            'repository': {'pullRequest': <String, Object?>{}},
          },
        });
      }
      return _fail('unexpected');
    });
    final service = ForgeActionService(
      resolver: ForgeResolver(transport: forge),
      runGit: _FakeGit().run,
    );
    for (final request in [
      {
        'type': CheckoutForgeSetAutoMergeRequest.modernType,
        'cwd': '/repo',
        'enabled': true,
        'requestId': 'missing',
      },
      {
        'type': CheckoutForgeSetAutoMergeRequest.modernType,
        'cwd': '/repo',
        'enabled': false,
        'mergeMethod': 'merge',
        'requestId': 'extra',
      },
    ]) {
      final response = CheckoutForgeSetAutoMergeResponse.fromJson(
        (await service.handle(request))!,
      );
      expect(response.success, isFalse);
      expect(response.error?.code, CheckoutErrorCode.notAllowed);
      expect(response.error?.message, contains('mergeMethod'));
    }
  });
}

final class _FakeGit {
  _FakeGit({
    this.insideRepo = true,
    this.branch = 'feature',
    this.remote = 'git@github.com:acme/repo.git',
    this.symbolicBase = 'origin/main',
    this.mainExists = true,
    this.masterExists = false,
    this.pushFails = false,
  });

  final bool insideRepo;
  final String branch;
  final String remote;
  final String symbolicBase;
  final bool mainExists;
  final bool masterExists;
  final bool pushFails;
  final List<String> calls = [];

  Future<GitResult> run(
    List<String> args, {
    required String cwd,
    bool check = true,
  }) async {
    calls.add(args.join(' '));
    final key = args.join(' ');
    return switch (key) {
      'rev-parse --is-inside-work-tree' => _git(
        insideRepo ? 'true\n' : '',
        ok: insideRepo,
      ),
      'symbolic-ref --quiet --short HEAD' => _git(
        branch.isEmpty ? '' : '$branch\n',
        ok: branch.isNotEmpty,
      ),
      'rev-parse HEAD' => _git('abc\n'),
      'config --get remote.origin.url' => _git(
        remote.isEmpty ? '' : '$remote\n',
        ok: remote.isNotEmpty,
      ),
      'symbolic-ref --quiet --short refs/remotes/origin/HEAD' => _git(
        symbolicBase.isEmpty ? '' : '$symbolicBase\n',
        ok: symbolicBase.isNotEmpty,
      ),
      'show-ref --verify --quiet refs/remotes/origin/main' => _git(
        '',
        ok: mainExists,
      ),
      'show-ref --verify --quiet refs/remotes/origin/master' => _git(
        '',
        ok: masterExists,
      ),
      'push -u origin feature' when pushFails => throw GitException(
        args: args,
        exitCode: 1,
        stderr: 'push rejected',
      ),
      'push -u origin feature' => _git(''),
      _ => _git('', ok: false),
    };
  }
}

final class _FakeForge implements ForgeCommandTransport {
  _FakeForge(this.handler);

  final ForgeCommandResult Function(String executable, List<String> args)
  handler;
  final List<List<String>> calls = [];

  @override
  Future<ForgeCommandResult> run(
    String executable,
    List<String> args, {
    required String cwd,
    Map<String, String> environment = const {},
    Duration timeout = const Duration(seconds: 30),
  }) async {
    calls.add(List.unmodifiable(args));
    return handler(executable, args);
  }
}

GitResult _git(String stdout, {bool ok = true}) =>
    GitResult(exitCode: ok ? 0 : 1, stdout: stdout, stderr: ok ? '' : 'failed');

ForgeCommandResult _ok(String stdout) =>
    ForgeCommandResult(exitCode: 0, stdout: stdout, stderr: '');

ForgeCommandResult _json(Object? value) => _ok(jsonEncode(value));

ForgeCommandResult _fail(String stderr) =>
    ForgeCommandResult(exitCode: 1, stdout: '', stderr: stderr);
