/// Provider configuration + credential messages (`provider.list`,
/// `provider.upsert`, `provider.delete`, `provider.credential.*`).
///
/// Providers are user-created instances, not a closed set: [ProviderConfig.id]
/// is an opaque string generated by the daemon. The only closed enum is
/// [ProviderKind], which selects the wire dialect (and therefore the backend).
library;

/// Which API dialect a provider speaks. Presets and hand-configured providers
/// both reduce to one of these.
enum ProviderKind {
  /// OpenAI Chat Completions (`POST {baseUrl}/chat/completions`).
  openaiCompatible,

  /// Anthropic Messages API (`POST {baseUrl}/messages`).
  anthropic;

  String get wire => switch (this) {
        ProviderKind.openaiCompatible => 'openai_compatible',
        ProviderKind.anthropic => 'anthropic',
      };

  /// Unknown values decode to [openaiCompatible] rather than throwing, so a
  /// newer daemon can't crash an older client.
  static ProviderKind fromWire(String? value) => switch (value) {
        'anthropic' => ProviderKind.anthropic,
        _ => ProviderKind.openaiCompatible,
      };
}

/// The editable shape of a provider. Never carries the API key — that lives in
/// the daemon's encrypted credential store, keyed by [id].
final class ProviderConfig {
  const ProviderConfig({
    required this.id,
    required this.displayName,
    required this.kind,
    required this.baseUrl,
    this.models = const [],
    this.extraHeaders = const {},
    this.maxTokens = defaultMaxTokens,
  });

  /// Anthropic's Messages API requires `max_tokens` on every request, so this
  /// is non-nullable with a generous default rather than optional.
  static const defaultMaxTokens = 8192;

  /// Daemon-generated opaque id. Empty on an upsert that creates a provider.
  final String id;
  final String displayName;
  final ProviderKind kind;

  /// API base URL without a trailing slash, and without the endpoint path
  /// (e.g. `https://api.openai.com/v1`, not `.../v1/chat/completions`).
  final String baseUrl;

  /// Seed models, used as the fallback when the provider's model endpoint is
  /// unreachable.
  final List<ProviderModel> models;

  /// Extra headers this provider requires beyond the auth header.
  final Map<String, String> extraHeaders;

  /// Per-request output cap. Required by the Anthropic dialect; unused by the
  /// OpenAI-compatible one.
  final int maxTokens;

  ProviderConfig copyWith({
    String? id,
    String? displayName,
    ProviderKind? kind,
    String? baseUrl,
    List<ProviderModel>? models,
    Map<String, String>? extraHeaders,
    int? maxTokens,
  }) =>
      ProviderConfig(
        id: id ?? this.id,
        displayName: displayName ?? this.displayName,
        kind: kind ?? this.kind,
        baseUrl: baseUrl ?? this.baseUrl,
        models: models ?? this.models,
        extraHeaders: extraHeaders ?? this.extraHeaders,
        maxTokens: maxTokens ?? this.maxTokens,
      );

  static ProviderConfig fromJson(Map<String, Object?> json) => ProviderConfig(
        id: (json['id'] as String?) ?? '',
        displayName: (json['displayName'] as String?) ?? '',
        kind: ProviderKind.fromWire(json['kind'] as String?),
        baseUrl: (json['baseUrl'] as String?) ?? '',
        models: ((json['models'] as List?) ?? const [])
            .cast<Map<String, Object?>>()
            .map(ProviderModel.fromJson)
            .toList(),
        extraHeaders: ((json['extraHeaders'] as Map?) ?? const {})
            .cast<String, Object?>()
            .map((key, value) => MapEntry(key, '$value')),
        maxTokens: (json['maxTokens'] as num?)?.toInt() ?? defaultMaxTokens,
      );

  Map<String, Object?> toJson() => {
        'id': id,
        'displayName': displayName,
        'kind': kind.wire,
        'baseUrl': baseUrl,
        'models': models.map((m) => m.toJson()).toList(),
        'extraHeaders': extraHeaders,
        'maxTokens': maxTokens,
      };
}

/// A provider as reported by `provider.list` — config plus runtime state
/// (whether a key is stored, and the live model list).
final class ProviderInfo {
  const ProviderInfo({
    required this.id,
    required this.displayName,
    required this.kind,
    required this.baseUrl,
    required this.configured,
    this.models = const [],
    this.unavailableReason,
    this.maxTokens = ProviderConfig.defaultMaxTokens,
    this.extraHeaders = const {},
  });

  final String id;
  final String displayName;
  final ProviderKind kind;
  final String baseUrl;

  /// Whether an API key is stored for this provider.
  final bool configured;

  /// Live models when [configured] (fetched from the provider), else the seed
  /// list from the config.
  final List<ProviderModel> models;
  final String? unavailableReason;
  final int maxTokens;
  final Map<String, String> extraHeaders;

  /// The editable subset, for seeding an edit form. Round-trips every field a
  /// user can change, so an edit never silently drops headers or maxTokens.
  ProviderConfig toConfig() => ProviderConfig(
        id: id,
        displayName: displayName,
        kind: kind,
        baseUrl: baseUrl,
        models: models,
        extraHeaders: extraHeaders,
        maxTokens: maxTokens,
      );

  static ProviderInfo fromJson(Map<String, Object?> json) => ProviderInfo(
        id: (json['id'] as String?) ?? '',
        displayName: (json['displayName'] as String?) ?? '',
        kind: ProviderKind.fromWire(json['kind'] as String?),
        baseUrl: (json['baseUrl'] as String?) ?? '',
        configured: (json['configured'] as bool?) ?? false,
        models: ((json['models'] as List?) ?? const [])
            .cast<Map<String, Object?>>()
            .map(ProviderModel.fromJson)
            .toList(),
        unavailableReason: json['unavailableReason'] as String?,
        maxTokens: (json['maxTokens'] as num?)?.toInt() ??
            ProviderConfig.defaultMaxTokens,
        extraHeaders: ((json['extraHeaders'] as Map?) ?? const {})
            .cast<String, Object?>()
            .map((key, value) => MapEntry(key, '$value')),
      );

  Map<String, Object?> toJson() => {
        'id': id,
        'displayName': displayName,
        'kind': kind.wire,
        'baseUrl': baseUrl,
        'configured': configured,
        'models': models.map((m) => m.toJson()).toList(),
        if (unavailableReason != null) 'unavailableReason': unavailableReason,
        'maxTokens': maxTokens,
        'extraHeaders': extraHeaders,
      };
}

final class ProviderModel {
  const ProviderModel({required this.id, required this.displayName});

  final String id;
  final String displayName;

  static ProviderModel fromJson(Map<String, Object?> json) => ProviderModel(
        id: json['id'] as String,
        displayName: (json['displayName'] as String?) ?? json['id'] as String,
      );

  Map<String, Object?> toJson() => {'id': id, 'displayName': displayName};
}

final class ProviderListResponse {
  const ProviderListResponse({required this.providers});

  final List<ProviderInfo> providers;

  static ProviderListResponse fromJson(Map<String, Object?> json) =>
      ProviderListResponse(
        providers: ((json['providers'] as List?) ?? const [])
            .cast<Map<String, Object?>>()
            .map(ProviderInfo.fromJson)
            .toList(),
      );

  Map<String, Object?> toJson() => {
        'providers': providers.map((p) => p.toJson()).toList(),
      };
}

/// Response to `provider.upsert.request` — the stored config, with the
/// daemon-assigned [ProviderConfig.id] filled in on create.
final class ProviderUpsertResponse {
  const ProviderUpsertResponse({required this.config});

  final ProviderConfig config;

  static ProviderUpsertResponse fromJson(Map<String, Object?> json) =>
      ProviderUpsertResponse(
        config: ProviderConfig.fromJson(
          (json['config'] as Map?)?.cast<String, Object?>() ?? const {},
        ),
      );

  Map<String, Object?> toJson() => {'config': config.toJson()};
}

/// Result of `provider.credential.test.request` — attempts a lightweight call
/// against the provider's API to confirm the stored (or given) key works.
final class ProviderCredentialTestResult {
  const ProviderCredentialTestResult({required this.ok, this.error});

  final bool ok;
  final String? error;

  static ProviderCredentialTestResult fromJson(Map<String, Object?> json) =>
      ProviderCredentialTestResult(
        ok: (json['ok'] as bool?) ?? false,
        error: json['error'] as String?,
      );

  Map<String, Object?> toJson() =>
      {'ok': ok, if (error != null) 'error': error};
}
