import 'package:agent_protocol/agent_protocol.dart';

import '../git/git_runner.dart';
import 'forge_cli.dart';
import 'forge_resolver.dart';
import 'workspace_forge_status_service.dart';

typedef ForgeActionGitRunner =
    Future<GitResult> Function(
      List<String> args, {
      required String cwd,
      bool check,
    });

final class ForgeActionService {
  ForgeActionService({
    required this.resolver,
    WorkspaceForgeStatusService? statusService,
    ForgeActionGitRunner? runGit,
  }) : statusService =
           statusService ?? WorkspaceForgeStatusService(resolver: resolver),
       _runGit = runGit ?? const GitRunner().run;

  final ForgeResolver resolver;
  final WorkspaceForgeStatusService statusService;
  final ForgeActionGitRunner _runGit;

  Future<Map<String, Object?>?> handle(Map<String, Object?> message) async {
    return switch (message['type']) {
      CheckoutPrCreateRequest.type => _create(
        CheckoutPrCreateRequest.fromJson(message),
      ),
      CheckoutPrMergeRequest.type => _merge(
        CheckoutPrMergeRequest.fromJson(message),
      ),
      CheckoutForgeSetAutoMergeRequest.modernType ||
      CheckoutForgeSetAutoMergeRequest.legacyGithubType => _setAutoMerge(
        CheckoutForgeSetAutoMergeRequest.fromJson(message),
      ),
      _ => null,
    };
  }

  Future<Map<String, Object?>> _create(CheckoutPrCreateRequest request) async {
    try {
      final context = await _context(request.cwd);
      final base = await _resolveBaseRef(request.cwd, request.baseRef);
      var title = request.title?.trim() ?? '';
      var body = request.body?.trim() ?? '';
      if (title.isEmpty) title = 'Update changes';
      if (body.isEmpty) body = 'Automated PR generated by Tinyrack.';

      await _runGit(
        ['push', '-u', 'origin', context.headRef],
        cwd: request.cwd,
        check: true,
      );
      final result = await context.resolution.adapter.createPullRequest(
        cwd: request.cwd,
        title: title,
        body: body,
        head: context.headRef,
        base: base,
        repositoryOwner: context.location.owner!,
        repositoryName: context.location.repo!,
      );
      statusService.invalidate(request.cwd);
      return CheckoutPrCreateResponse(
        cwd: request.cwd,
        url: result.url,
        number: result.number,
        error: null,
        requestId: request.requestId,
      ).toJson();
    } catch (error) {
      return CheckoutPrCreateResponse(
        cwd: request.cwd,
        url: null,
        number: null,
        error: _checkoutError(error),
        requestId: request.requestId,
      ).toJson();
    }
  }

  Future<Map<String, Object?>> _merge(CheckoutPrMergeRequest request) async {
    try {
      final context = await _context(request.cwd);
      final status = await context.resolution.adapter
          .getCurrentPullRequestStatus(
            cwd: request.cwd,
            headRef: context.headRef,
            headSha: context.headSha,
            repositoryOwner: context.location.owner,
            repositoryName: context.location.repo,
          );
      final number = status?.number;
      if (status == null || number == null) {
        throw StateError('No pull request found for the current branch');
      }
      await context.resolution.adapter.mergePullRequest(
        cwd: request.cwd,
        number: number,
        mergeMethod: request.mergeMethod,
        status: status,
      );
      statusService.invalidate(request.cwd);
      return CheckoutPrMergeResponse(
        cwd: request.cwd,
        success: true,
        error: null,
        requestId: request.requestId,
      ).toJson();
    } catch (error) {
      return CheckoutPrMergeResponse(
        cwd: request.cwd,
        success: false,
        error: _checkoutError(error),
        requestId: request.requestId,
      ).toJson();
    }
  }

  Future<Map<String, Object?>> _setAutoMerge(
    CheckoutForgeSetAutoMergeRequest request,
  ) async {
    try {
      final context = await _context(request.cwd);
      final status = await context.resolution.adapter
          .getCurrentPullRequestStatus(
            cwd: request.cwd,
            headRef: context.headRef,
            headSha: context.headSha,
            repositoryOwner: context.location.owner,
            repositoryName: context.location.repo,
          );
      final number = status?.number;
      if (status == null || number == null) {
        throw StateError('No pull request found for the current branch');
      }
      if (request.enabled) {
        final mergeMethod = request.mergeMethod;
        if (mergeMethod == null) {
          throw StateError('mergeMethod is required when enabling auto-merge');
        }
        await context.resolution.adapter.enablePullRequestAutoMerge(
          cwd: request.cwd,
          number: number,
          mergeMethod: mergeMethod,
          status: status,
        );
      } else {
        if (request.mergeMethod != null) {
          throw StateError(
            'mergeMethod is not allowed when disabling auto-merge',
          );
        }
        await context.resolution.adapter.disablePullRequestAutoMerge(
          cwd: request.cwd,
          number: number,
          status: status,
        );
      }
      statusService.invalidate(request.cwd);
      return CheckoutForgeSetAutoMergeResponse(
        type: request.responseType,
        cwd: request.cwd,
        enabled: request.enabled,
        success: true,
        error: null,
        requestId: request.requestId,
      ).toJson();
    } catch (error) {
      return CheckoutForgeSetAutoMergeResponse(
        type: request.responseType,
        cwd: request.cwd,
        enabled: request.enabled,
        success: false,
        error: _checkoutError(error),
        requestId: request.requestId,
      ).toJson();
    }
  }

  Future<_ForgeActionContext> _context(String cwd) async {
    final inside = await _runGit(
      ['rev-parse', '--is-inside-work-tree'],
      cwd: cwd,
      check: false,
    );
    if (!inside.ok || inside.stdout.trim() != 'true') {
      throw const _NotGitRepoError();
    }
    final branch = await _runGit(
      ['symbolic-ref', '--quiet', '--short', 'HEAD'],
      cwd: cwd,
      check: false,
    );
    final headRef = branch.ok ? branch.stdout.trim() : '';
    if (headRef.isEmpty || headRef == 'HEAD') {
      throw StateError('Unable to determine current branch');
    }
    final sha = await _runGit(['rev-parse', 'HEAD'], cwd: cwd, check: true);
    final remote = await _runGit(
      ['config', '--get', 'remote.origin.url'],
      cwd: cwd,
      check: false,
    );
    final remoteUrl = remote.ok ? remote.stdout.trim() : '';
    final location = parseGitRemoteLocation(remoteUrl);
    if (location == null || location.owner == null || location.repo == null) {
      throw StateError("Remote 'origin' is not configured.");
    }
    final resolution = await resolver.resolveFromRemoteUrlAsync(
      remoteUrl,
      cwd: cwd,
    );
    if (resolution == null ||
        !await resolution.adapter.isAuthenticated(
          cwd: cwd,
          host: resolution.host,
        )) {
      throw StateError('Forge authentication is unavailable');
    }
    return _ForgeActionContext(
      location: location,
      resolution: resolution,
      headRef: headRef,
      headSha: sha.stdout.trim(),
    );
  }

  Future<String> _resolveBaseRef(String cwd, String? requested) async {
    final explicit = requested?.trim() ?? '';
    if (explicit.isNotEmpty) return _normalizeBranch(explicit);
    final symbolic = await _runGit(
      ['symbolic-ref', '--quiet', '--short', 'refs/remotes/origin/HEAD'],
      cwd: cwd,
      check: false,
    );
    if (symbolic.ok && symbolic.stdout.trim().isNotEmpty) {
      return _normalizeBranch(symbolic.stdout.trim());
    }
    for (final candidate in const ['main', 'master']) {
      final exists = await _runGit(
        ['show-ref', '--verify', '--quiet', 'refs/remotes/origin/$candidate'],
        cwd: cwd,
        check: false,
      );
      if (exists.ok) return candidate;
    }
    throw StateError('Unable to determine base branch for PR');
  }
}

final class _ForgeActionContext {
  const _ForgeActionContext({
    required this.location,
    required this.resolution,
    required this.headRef,
    required this.headSha,
  });

  final GitRemoteLocation location;
  final ForgeResolution resolution;
  final String headRef;
  final String headSha;
}

final class _NotGitRepoError implements Exception {
  const _NotGitRepoError();
}

String _normalizeBranch(String value) {
  const prefixes = ['refs/remotes/', 'refs/heads/', 'origin/'];
  var normalized = value;
  for (final prefix in prefixes) {
    if (normalized.startsWith(prefix)) {
      normalized = normalized.substring(prefix.length);
    }
  }
  return normalized;
}

CheckoutError _checkoutError(Object error) {
  final code = switch (error) {
    _NotGitRepoError() => CheckoutErrorCode.notGitRepo,
    StateError() ||
    ArgumentError() ||
    ForgeAuthenticationException() => CheckoutErrorCode.notAllowed,
    _ => CheckoutErrorCode.unknown,
  };
  final String message;
  if (error is StateError) {
    message = '${error.message}';
  } else if (error is ArgumentError) {
    message = '${error.message}';
  } else if (error is ForgeCliException) {
    message = error.message;
  } else if (error is GitException) {
    message = error.message;
  } else if (error is _NotGitRepoError) {
    message = 'Not a git repository';
  } else {
    message = error.toString();
  }
  return CheckoutError(code: code, message: message);
}
